services:
  nginx:
    image: ghcr.io/theanibalos/streamcoreos-front:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/theanibalos/streamcoreos:latest
    env_file:
      - .env
    environment:
      SQLITE_DB_PATH: data/database.db
    volumes:
      - ./data:/app/data
    command: sh -c "uv run main.py"
    restart: unless-stopped
